# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ea0506e59fa7058d648807d9e536ab0df8dbb9d55ad6287619a65e8fe19b0076cb52c9ada947e37f1682d3ead8db0bdd789b1cf15f12090f883cfb4ba25b4c2

test:
  secret_key_base: 45cc491c4bc9f85aab280b682dfbd6bc5db9adf04cab30c2192ead6fced80e787c37e0cc13aed79e9427da2b69d81b6c30f9200f1862d9ec043db6be50597cbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
